### ISSUE TITLE
Add Headers in func NewRequest

### ISSUE THREAD

**Issue by k-batista** [xinsnake/go-http-digest-auth-client#17]
In func NewRequest, could create parameter with headers.

I had a problem with an api, I had to send Content-Type. I made the following change:

```
func (dr *DigestRequest) UpdateRequest(username, password, method, uri, body string) *DigestRequest {
	dr.Body = body
	dr.Method = method
	dr.Password = password
	dr.URI = uri
	dr.Username = username
	dr.Header = make(map[string][]string)
	
        //HERE
       dr.Header["Content-Type"] = []string{"application/json"}

	return dr
}
```

**Comment by bmess** [comment]
I ran into the same problem with the `.RoundTrip()` function making a new request and ignoring the headers.

**Comment by k-batista** [comment]
Resolve with this code
dr := dac.NewRequest("user", "pass", "GET", url, string(mapB))
dr.Header.Set("Content-Type", "application/json")

**Comment by bmess** [comment]
Considering the headers are part of an existing request, I think it should be standard to copy all headers as well.  I'll create a new issue/pull request.
