### ISSUE TITLE
Provide a http.RoundTripper implementation

### ISSUE THREAD

**Issue by F21** [xinsnake/go-http-digest-auth-client#2]
It would be nice if your package can provide a `http.RoundTripper` implementation similar to https://godoc.org/github.com/bobziuchkovski/digest

This would allow your package to be used with a `http.Client` which can then be used with the `ctxhttp` package.

**Comment by xinsnake** [comment]
Okay I'll see what I can do. Seems to be a great idea. Thanks for your suggestion!

**Comment by xinsnake** [comment]
#3 Just implemented it along with the documentation.
