### ISSUE TITLE
Release tags are in the incorrect format

### ISSUE THREAD

**Issue by F21** [xinsnake/go-http-digest-auth-client#20]
The last 2 releases were tagged without the `v` in front: `0.5.0` and `0.6.0`. As a result, these 2 releases are not discoverable via go modules. See https://pkg.go.dev/github.com/xinsnake/go-http-digest-auth-client?tab=versions for the list of discoverable releases.

The `0.5.0` and `0.6.0`  releases should be retagged to `v0.5.0` and `v0.6.0` respectively.

**Comment by F21** [comment]
ping @xinsnake

**Comment by xinsnake** [comment]
Thanks for reporting. Sorry for the delay.
