### ISSUE TITLE
regex failed

### ISSUE THREAD

**Issue by ahaooahaz** [xinsnake/go-http-digest-auth-client#24]
test string: "Digest realm=\"e29072b1b78a1e4d7bfdec11\", domain=\"::\", qop=\"auth\", nonce=\"nonce\", opaque=\"\", algorithm=\"MD5\", stale=\"FALSE\"", regex error when param has empty string

**Comment by xinsnake** [comment]
Thanks for your report. Due to time limit on my side I won't be able to maintain this package. Please consider using some other library like https://github.com/rkl-/digest. Thanks for your support!
