### ISSUE TITLE
Leaking goroutines and filedescriptors

### ISSUE THREAD

**Issue by hfurhoff** [xinsnake/go-http-digest-auth-client#27]
Using pprof i noticed alot of hanging goroutines and in prometheus i could see that filedescriptors was accumulating. Traced the leak down to be from this package, switched to [github.com/rkl-/digest](https://github.com/rkl-/digest) instead and the leak is now gone. Thought i would let you know though.

**Comment by xinsnake** [comment]
Thanks for your report. Due to time limit on my side I won't be able to maintain this package. Glad that you can find a working replacement. Thanks for your support!

**Comment by TJDev** [comment]
@hfurhoff [github.com/rkl-/digest](https://github.com/rkl-/digest) doesn't exist anymore. Do you still use it or do you have any replacement for it?
