### ISSUE TITLE
parameter for timeout

### ISSUE THREAD

**Issue by dh1tw** [xinsnake/go-http-digest-auth-client#5]
Hi @xinsnake,
thanks for this neat library! I'm using it to grab some pictures from an IP Camera which requires the digest based authentication. 

The only wish I have is to be able to set a shorter timeout. Currently the timeout is hard coded to 30 seconds. 

Maybe an implementation using the context package would make sense. `Context.WithTimeout` could be an adequate solution.

**Comment by xinsnake** [comment]
Hi @dh1tw Thanks for your suggestion. I'll be having a look.

**Comment by xinsnake** [comment]
After looking at the forks people have different ways of implementing the options needed and none of them really stands out. Leaving this as it is and if this needs to be standardised we can reopen this and think about how can we solve them.
