### ISSUE TITLE
HTTP Headers not recognized.

### ISSUE THREAD

**Issue by mlsaito** [xinsnake/go-http-digest-auth-client#8]
I'm trying to do an HTTP POST using this library with the second approach but http headers are not recognized.

```
transport := dig.NewTransport(username, password)
req, err := http.NewRequest("POST", fullUri, someJsonData)
req.Header.Set("Content-Type", "application/json")
resp, _ := transport.RoundTrip(req)
```

Tried to do a POST on to https://requestb.in and Content-Type header is indeed not received.
Tried to use another library but this exact same code worked.

I haven't looked into the pull requests but this PR https://github.com/xinsnake/go-http-digest-auth-client/pull/6 might have already solved this problem.

**Comment by xinsnake** [comment]
@mlsaito  Sorry for the delayed response. Can you please confirm whether this issue still require attention? If yes please re-open. Thanks!

**Comment by marinsalinas** [comment]
Hello @xinsnake, 

I'm trying to use this library through my own http.Client, but the transport does not pass the headers for the authenticated request.

I found this forked repo: I test it and this works.

https://github.com/akshaykarle/go-http-digest-auth-client/commit/e991a929247d9f8263227e39d5e395c85674811a

Can you add this solution to the main repo?

thanks!

**Comment by xinsnake** [comment]
@marinsalinas  Feel free to submit a PR. Thanks!

**Comment by x1unix** [comment]
This issue is actual and should be reopened
